import { withLayout } from "@/layout/Layout/Layout";
import { GetStaticProps } from "next";
import Head from "next/head";
import axios from "axios";
import { HomeProps, MenuItem } from "@/interfaces/menu";
import { FC } from "react";

export function Home({ menu, firstCategory }: HomeProps): JSX.Element {
	return (
		<>
			<Head>
				<title>Courses shop</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>Главная страница</main>
			<div>
				{!!menu.length &&
					menu.map((menu, id) => (
						<div key={id}>{menu.pages.map((menu) => menu.title)}</div>
					))}
			</div>
		</>
	);
}

export default withLayout(Home as FC);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
	const firstCategory = 0;
	console.log(process.env.NEXT_PUBLIC_DOMAIN);
	const reqUrl = process.env.NEXT_PUBLIC_DOMAIN + "/api/top-page/find";
	const reqBody = {
		firstCategory: 0,
	};

	const { data: menu } = await axios.post<MenuItem[]>(reqUrl, reqBody);

	return {
		props: {
			menu,
			firstCategory,
		},
	};
};
