import { withLayout } from "@/layout/Layout/Layout";
import Head from "next/head";

export function Home() {
    return (
        <>
            <Head>
                <title>Courses shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>Главная страница</main>
        </>
    );
}

export default withLayout(Home);
